import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const SOURCE_URL = 'https://models.dev/api.json'
const OUTPUT = fileURLToPath(new URL('../src/chat/model-capabilities.ts', import.meta.url))

interface SourceModel {
  reasoning?: boolean
  reasoning_options?: Array<{ type?: string; values?: string[] }>
}

interface SourceProvider {
  api?: string
  models?: Record<string, SourceModel>
}

interface Capability {
  readonly efforts: Readonly<Record<string, string>>
}

const run = async (): Promise<void> => {
  const response = await fetch(SOURCE_URL, { signal: AbortSignal.timeout(30_000) })
  if (!response.ok) throw new Error(`models.dev returned ${response.status}`)
  const source = (await response.json()) as Record<string, SourceProvider>

  const capabilities = new Map<string, Capability>()
  const providerIndex: Array<{ url: string; id: string }> = []
  const seenUrls = new Set<string>()

  for (const [providerId, provider] of Object.entries(source)) {
    const api = typeof provider.api === 'string' ? provider.api : undefined
    if (api !== undefined && !seenUrls.has(api)) {
      seenUrls.add(api)
      providerIndex.push({ url: api, id: providerId })
    }
    for (const [modelId, model] of Object.entries(provider.models ?? {})) {
      if (model.reasoning !== true) continue
      // Wire values stay null for "off": databases record a vendor's native
      // capability surface, but OpenAI-compatible relays routinely reject the
      // none/off wire strings, so selecting Off must mean "send nothing".
      const efforts: Record<string, string | null> = {}
      for (const option of model.reasoning_options ?? []) {
        if (option.type !== 'effort') continue
        for (const rawValue of option.values ?? []) {
          if (typeof rawValue !== 'string' || rawValue.length === 0) continue
          const value = rawValue.toLowerCase()
          const level = value === 'none' ? 'off' : value
          if (level !== 'off' && level !== 'minimal' && level !== 'low' && level !== 'medium' && level !== 'high' && level !== 'xhigh' && level !== 'max') continue
          efforts[level] = level === 'off' ? null : value
        }
      }
      if (Object.keys(efforts).length === 0) continue
      capabilities.set(`${providerId}\u0000${modelId.toLowerCase()}`, { efforts })
    }
  }

  const effortSets = [...new Set(capabilities.values().map(capability => JSON.stringify(capability.efforts)))]
  const effortTable = effortSets.map(set => JSON.parse(set) as Record<string, string | null>)
  const effortIndexOf = (efforts: Record<string, string | null>): number =>
    effortSets.indexOf(JSON.stringify(efforts))

  const entries: string[] = []
  for (const [key, capability] of capabilities) {
    const separator = key.indexOf('\u0000')
    entries.push(`${key.slice(0, separator)}\u0001${key.slice(separator + 1)}\u0001${effortIndexOf(capability.efforts)}`)
  }

  const urls = providerIndex.map(entry => `${entry.url}\u0001${entry.id}`)

  writeFileSync(OUTPUT, `// Generated by scripts/update-capabilities.ts from ${SOURCE_URL}. Do not edit.
export const EFFORT_TABLE: ReadonlyArray<Record<string, string | null>> = ${JSON.stringify(effortTable)}

export const MODEL_INDEX: string = ${JSON.stringify(entries.join('\u0002'))}

export const PROVIDER_URLS: string = ${JSON.stringify(urls.join('\u0002'))}
`)
  console.log(`wrote ${OUTPUT}: ${effortTable.length} effort sets, ${entries.length} model entries, ${urls.length} provider urls`)
}

await run()
