import './runtime/prod-react.ts'

export { Dialog, CloseGuardContext } from './ui/dialog/dialog.tsx'
export type { DialogProps, DialogHandle } from './ui/dialog/dialog.tsx'
export type { DialogRow, DialogItem, DialogFocus, TextItem } from './ui/dialog/items.ts'
export { asTextItem } from './ui/dialog/items.ts'
export type { DialogFooterLine } from './ui/dialog/geometry.ts'
export { rowHeight, wrapStatusLines } from './ui/dialog/geometry.ts'
export { registerWidget } from './ui/widgets/registry.ts'
export { PanelSurface, panelLegend, panelAnchorRow } from './ui/panels/exports.ts'
export type { PanelRow, PanelHint, PanelLegendOptions, PanelPointerHandle } from './ui/panels/exports.ts'
