export const colors = {
  userBubbleBackground: '#3a3a3a',
  aiBubbleBackground: '#464646',
  errorText: '#ff6b6b',
  toolLabel: '#5fd7ff',
  toolBodyText: '#808080',
  modelText: '#ffffff',
  cwdText: '#ffffff',
  success: '#4caf50',
  dialogBackground: '#000000',
  mdBold: '#ff8800',
  mdInlineCode: '#4caf50',
  mdList: '#5fd7ff',
  mdH1: '#c678dd',
  mdH2: '#c678dd',
  mdH3: '#5fd7ff',
  mdCode: '#d4d4d4',
  mdCodeNoLang: '#5fd7ff',
  codeComment: '#6a9955',
  codeString: '#ce9178',
  codeNumber: '#b5cea8',
  codeKeyword: '#c586c0',
  codeFunction: '#dcdcaa',
  codeType: '#4ec9b0',
  codeVariable: '#9cdcfe',
  codeConstant: '#4fc1ff',
  codeOperator: '#d4d4d4',
  codeCommentDark: '#4e7a3f',
  codeStringDark: '#93684f',
  codeNumberDark: '#7f9c73',
  codeKeywordDark: '#8d5c8a',
  codeFunctionDark: '#9c9a6e',
  codeTypeDark: '#38897a',
  codeVariableDark: '#6e9cb3',
  codeConstantDark: '#3888b3',
  codeOperatorDark: '#9a9a9a',
  thinkInlineCode: '#2e7d32',
  thinkQuote: '#9a6a4a',
  codeNoLangDark: '#3f96b3',
} as const

export const permissionModes = {
  'workspace-write': { color: '#3a3a3a', name: 'Workspace Write' },
  'danger-full-access': { color: '#6b2a2a', name: 'Full access' },
  'read-only': { color: '#6b5f2a', name: 'Read Only' },
} as const

export function permissionModeInfo(mode: string): { color: string; name: string } {
  return permissionModes[mode as keyof typeof permissionModes] ?? { color: colors.userBubbleBackground, name: mode }
}